<?php
$title = 'Cadastrar um novo Canal';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->basePath('application/canal/add'));
$form->prepare();
?>
<div class="page-header">
    <?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formHidden($form->get('id')); ?>
    <div class="form-group">
        <label for="nome" class="col-sm-2 control-label">Nome</label>
        <div class="col-sm-3">
            <?php echo $this->formRow($form->get('nome')); ?>
        </div>
    </div>
    <div class="form-group">
        <label for="url" class="col-sm-2 control-label">Url de Canal</label>
        <div class="col-sm-3">
            <?php echo $this->formRow($form->get('url')); ?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-4">
            <?php echo $this->formSubmit($form->get('submit')); ?>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>
    <div class="row">
        <nav class="menu">
            <li><a href="/application/canal/list">Canal Listagem</a></li>
        </nav>
    </div>
</div>