<table class="table table-bordered">
    <tr>
        <th>
            ID
        </th>
        <th>
            Nome
        </th>
        <th>
            URL
        </th>
        <th>
            Ação
        </th>
    </tr>
    <?php foreach ($canais as $canal): ?>
        <tr>
            <td>
                <?php echo $canal->id; ?>
            </td>
            <td>
                <?php echo $canal->nome; ?>
            </td>
            <td>
                <?php echo $canal->url; ?>
            </td>
            <td>
                <a href="<?php echo $this->basePath('application/canal/edit/' . $canal->id) ?>"><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                <a href="<?php echo $this->basePath('application/canal/delete/' . $canal->id) ?>"><span class="glyphicon glyphicon-trash"></span> Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<div class="row">
    <nav class="menu">
        <li><a href="/canal/add">Adicionar Canal</a></li>
    </nav>
</div>


