<div class="jumbotron">
    <a href="/sair" class="pull-right btn btn-large btn-default" ><i class="glyphicon glyphicon-log-out"></i> Sair</a>
    <h1><?php echo sprintf($this->translate('Bem vindo ao projeto do Curso %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><a class="btn btn-success btn-lg" href="https://github.com/edianogama/cursozend2" target="_blank"><?php echo $this->translate('Este Projeto No GitHub') ?> &raquo;</a></p>
</div>

<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?php echo $this->translate('Cadastro de Usuario') ?></h3>
        </div>
        <div class="panel-body">
            <div class="col-md-3">
                <a class="btn btn-large btn-success"  style="display: block; width: 100%;"  href="/usuario">
                    <i class="glyphicon glyphicon-wrench"></i> Usuario</a>
            </div>
            <div class="col-md-3">
                <a class="btn btn-success" style="display: block; width: 100%;"  href="/perfil" >
                    <i class="glyphicon glyphicon-user"></i> Perfil</a>

            </div>
            <div class="col-md-3">
                <a class="btn btn-success " style="display: block; width: 100%;"  href="/canal" >
                    <i class="glyphicon glyphicon-facetime-video"></i> Canal</a>
            </div>
            <div class="col-md-3">
                <a class="btn btn-success "  style="display: block; width: 100%;" href="/video">
                    <i class="glyphicon glyphicon-play"></i> Videos</a>
            </div>
        </div>
    </div>


</div>
