<table class="table table-bordered">
    <tr>
        <th>
            ID
        </th>
        <th>
            Nome
        </th>
        <th>
            Ação
        </th>
    </tr>
    <?php foreach ($perfis as $perfil): ?>
        <tr>
            <td>
                <?php echo $perfil->id; ?>
            </td>
            <td>
                <?php echo $perfil->nome; ?>
            </td>
            <td>
                <a href="<?php echo $this->basePath('application/perfil/edit/' . $perfil->id) ?>"><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                <a href="<?php echo $this->basePath('application/perfil/delete/' . $perfil->id) ?>"><span class="glyphicon glyphicon-trash"></span> Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<div class="row">
    <nav class="menu">
        <li><a href="/application/perfil/add">Adicionar perfil</a></li>
    </nav>
</div>


