<a href="/perfil/add" class="btn btn-info">
    <i class="glyphicon glyphicon-plus"></i> Novo Perfil
</a>
<table class="table table-bordered">
    <tr>
        <th>
            ID
        </th>
        <th>
            Nome
        </th>
        <th>
            Ação
        </th>
    </tr>
    <?php foreach ($perfis as $perfil): ?>
        <tr>
            <td>
                <?php echo $perfil->id; ?>
            </td>
            <td>
                <?php echo $perfil->nome; ?>
            </td>
            <td>
                <a href="<?php echo $this->basePath('perfil/edit/' . $perfil->id) ?>"><span class="glyphicon glyphicon-pencil"></span> Editar</a>
                <a href="<?php echo $this->basePath('perfil/delete/' . $perfil->id) ?>"><span class="glyphicon glyphicon-trash"></span> Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

